/**
 * The UniPay QR contract.
 *
 * A student QR carries an identifier and NOTHING ELSE — no name, no balance.
 * The merchant app resolves the identifier against the server to get the
 * current balance, so a stale or photographed QR can never assert a balance.
 *
 * Canonical payload (what we generate):
 *   {"type":"UNIPAY_STUDENT","studentId":"24SCSE1010531","v":1}
 *
 * The parser is deliberately permissive about the OTHER shapes a real-world QR
 * arrives in, because the identifier is not a secret and recognising it grants
 * nothing on its own — the server still resolves the wallet and the student
 * still authorises with their PIN before a single rupee moves. Accepted:
 *
 *   {"type":"UNIPAY_STUDENT","studentId":"24SCSE1010531"}   canonical JSON
 *   UNIPAY:24SCSE1010531                                     compact form
 *   unipay-24scse1010531 / UNIPAY_24SCSE1010531              separator variants
 *   https://example.com/s/24SCSE1010531                      URL-wrapped
 *   https://x.com/?studentId=24SCSE1010531                   URL query
 *   24scse1010531                                            bare admission no.
 *   24 SCSE 1010531                                          as printed on a card
 *
 * Rejected: anything containing characters outside [A-Za-z0-9 _-], so a QR
 * holding a sentence or a vCard cannot be squashed into a lookalike ID.
 */

export const QR_VERSION = 1;

export function buildStudentQrPayload(studentId) {
  return JSON.stringify({ type: 'UNIPAY_STUDENT', studentId, v: QR_VERSION });
}

/** Short form kept on the student record for display/debugging. */
export function buildStudentQrIdentifier(studentId) {
  return `UNIPAY:${studentId}`;
}

/**
 * Parse whatever the camera decoded.
 * Returns `{ ok: true, studentId }` or `{ ok: false, message }`.
 */
export function parseStudentQr(raw) {
  const text = String(raw ?? '').trim();
  if (!text) return { ok: false, message: 'Invalid UniPay QR code.' };

  // JSON form
  if (text.startsWith('{')) {
    try {
      const parsed = JSON.parse(text);
      if (parsed?.type !== 'UNIPAY_STUDENT') return { ok: false, message: 'Invalid UniPay QR code.' };
      const studentId = normaliseId(parsed.studentId);
      if (!studentId) return { ok: false, message: 'Invalid UniPay QR code.' };
      return { ok: true, studentId };
    } catch {
      return { ok: false, message: 'Invalid UniPay QR code.' };
    }
  }

  // Compact form: UNIPAY:24SCSE1010531  (also tolerates unipay- / unipay_ /
  // a stray space, since hand-made QRs and printed cards vary)
  const prefixed = /^UNIPAY[:\-_\s]+([A-Za-z0-9\-_\s]{3,40})$/i.exec(text);
  if (prefixed) {
    const studentId = normaliseId(prefixed[1]);
    if (studentId) return { ok: true, studentId };
  }

  // URL form: any link whose last path segment or ?id=/?studentId= is an ID.
  // Covers QRs generated by third-party tools that wrap the value in a URL.
  if (/^https?:\/\//i.test(text)) {
    try {
      const url = new URL(text);
      const candidate =
        url.searchParams.get('studentId') ??
        url.searchParams.get('id') ??
        url.pathname.split('/').filter(Boolean).pop();
      // Also unverified, so the same digit rule applies: a link's last path
      // segment is very often an ordinary word ("/about", "/login").
      const studentId = normaliseId(candidate, { requireDigit: true });
      if (studentId) return { ok: true, studentId };
    } catch {
      /* not a parseable URL — fall through */
    }
  }

  // Bare identifier: the QR contains only the admission number, e.g.
  // "24scse1010531". This is what you get from a generic QR generator, or from
  // a printed university ID card that encodes the roll number and nothing else.
  // Accepting it is safe: the ID is only an identifier, and the server still
  // looks up the wallet and requires the student's PIN before any debit.
  const bare = normaliseId(text, { requireDigit: true });
  if (bare) return { ok: true, studentId: bare };

  return { ok: false, message: 'Invalid UniPay QR code.' };
}

/**
 * Normalise a candidate identifier.
 *
 * Separators (spaces, dashes, underscores) are stripped, because a printed card
 * may render an ID as "24 SCSE 1010531". Anything else disqualifies the string:
 * without that check a QR containing a sentence would have its letters squashed
 * together into something that looks like an ID, and we would "recognise" a
 * wallet that was never on the card.
 */
/**
 * Normalise a candidate identifier.
 *
 * `requireDigit` is applied only to the BARE form, where the QR gave us no
 * evidence it is a UniPay code at all. An admission number always contains a
 * digit ("24SCSE1010531") while a run of English words does not, so the rule
 * stops "hello world this is not an id" collapsing into a lookalike wallet id.
 * Payloads that explicitly declare themselves UniPay (the JSON form, or the
 * UNIPAY: prefix) skip the rule, so an all-letter ID still works there.
 */
function normaliseId(value, { requireDigit = false } = {}) {
  const raw = String(value ?? '').trim();
  if (!raw) return null;
  if (!/^[A-Za-z0-9\-_\s]+$/.test(raw)) return null;

  const id = raw.toUpperCase().replace(/[^A-Z0-9]/g, '');
  if (id.length < 3 || id.length > 32) return null;
  if (requireDigit && !/[0-9]/.test(id)) return null;

  return id;
}
